### PR TITLE
Fix SQL Server 2017 error during migration: "There is already an obje…

### PR DESCRIPTION
**Pull request by chrisvidal**
"There is already an object named 'user_group' in the database."
by simply renaming the index name

### CODE REVIEW

**Comment by LukeTowers** [comment]
Where is that user_group object coming from?

**Comment by chrisvidal** [comment]
That's a good question!
I did search inside all the sys objects of SQL Server and didn't find anything. Probably an existing index name linked to the Security in SQL Server?

the error happens when installing Rainlab.User during the migration on a clean oc install.

**Comment by LukeTowers** [comment]
@chrisvidal is the database completely clean too when installing?

**Comment by chrisvidal** [comment]
after OC installation,. SQL Server 2017 has created some `objects` here and there. I am not an expert on SQL Server at all, so I am not sure what it is creating. But there seem to have some security stuffs, some sys objects, etc...

**Comment by bennothommo** [comment]
@chrisvidal I've just done a quick search on the SQL Server docs and there's nothing to indicate that `user_group` is in any way a special term, so it seems more likely that perhaps your database is not clean.

**Comment by chrisvidal** [comment]
I did some research as well and didn't find anything.

The db was all brand new.

we installed Rainlab.Blog to test the installation of `group_concat` for SQL Server 2017 and it was successful,
then we installed Rainlab.User and find this migration error.

**Comment by LukeTowers** [comment]
The only think I can think of is if SQL Server 2017 has a global database namespace for combined primary key indexes since the backend user system also has a combined primary key index with the same columns provided as input. In most other DB drivers however since those are in different tables it shouldn't cause an issue. https://github.com/octobercms/october/blob/develop/modules/backend/database/migrations/2013_10_01_000003_Db_Backend_Users_Groups.php#L14.

If that's the case, then we might need to make some changes to the SQL Server grammar so that doesn't cause this issue. 

@chrisvidal can you create a new empty database, and this time before you run any of the migrations just make this PR's change to the migration file for the backend that I linked above and then see if adding the user plugin without this PR's changes works?

**Comment by chrisvidal** [comment]
Ooo that would make total sense @LukeTowers 

Alright I will give it a try, I will have access remotely to the server only tomorrow.

**Comment by chrisvidal** [comment]
@LukeTowers as I am using the wizard installer, when is the good time to make the change in the migration file?

**Comment by LukeTowers** [comment]
@chrisvidal just delete the database and recreate it after the installer has finished, and then run `php artisan october:up` after making changes to the migration file

**Comment by chrisvidal** [comment]
@LukeTowers you were right, after updating the backend user group migration, the Rainlab User plugin installation is smooth again.

**Comment by bennothommo** [comment]
@chrisvidal Classic Microsoft :(.

@LukeTowers given the above, I think changing the primary key group name should be fine. It shouldn't affect anyone who's already installed the plugin without any issues - we'll just have to note it down as a comment if we ever have to migrate that table further that the index might be called one of two names. Off the top of my head, I don't think there's anything specific in the grammar that we can change.

**Comment by LukeTowers** [comment]
Hmm, according to https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?redirectedfrom=MSDN&view=sql-server-2017 index names only have to be unique within the table or view, but this issue is happening even though both indexes exist within separate tables. According to https://nakulvachhrajani.com/2016/07/11/0376-sql-server-msg-2714-there-is-already-an-object-named-tablename-in-the-database/, this might be an issue with Deferred Name Resolution if both queries were being processed at the same time, but AFAIK they are run separately within the database. 

@chrisvidal can you try installing October into a clean database as one action (with no modifications) and then installing the RainLab.User plugin as a second separate action?

(Note for the future, the command is defined in `Illuminate\Database\Schema\Blueprint->indexCommand()`)

**Comment by chrisvidal** [comment]
> Hmm, according to https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?redirectedfrom=MSDN&view=sql-server-2017 index names only have to be unique within the table or view, but this issue is happening even though both indexes exist within separate tables. According to https://nakulvachhrajani.com/2016/07/11/0376-sql-server-msg-2714-there-is-already-an-object-named-tablename-in-the-database/, this might be an issue with Deferred Name Resolution if both queries were being processed at the same time, but AFAIK they are run separately within the database.

Reminding that we are using SQL Server 2017 on Windows 2019 here. 

> @chrisvidal can you try installing October into a clean database as one action (with no modifications) and then installing the RainLab.User plugin as a second separate action?

That is the process that we followed during the 1st installation and that raised the SQL State exception from SQL Server.

**Comment by LukeTowers** [comment]
> Reminding that we are using SQL Server 2017 on Windows 2019 here.

That's what the docs link is for is it not?

> That is the process that we followed during the 1st installation and that raised the SQL State exception from SQL Server.

Hmm, that most likely rules out the deferred name resolution then.

Is there any non-standard configuration being used that would cause the index names to not be scoped to the table they apply to?

**Comment by chrisvidal** [comment]
> > Reminding that we are using SQL Server 2017 on Windows 2019 here.
> 
> That's what the docs link is for is it not?

yes, I was referring to the article dated from 2016, I was wondering if SQL 2917 was out already,

> 
> > That is the process that we followed during the 1st installation and that raised the SQL State exception from SQL Server.
> 
> Hmm, that most likely rules out the deferred name resolution then.
> 
> Is there any non-standard configuration being used that would cause the index names to not be scoped to the table they apply to?

I have no idea, the server is set up by another hosting vendor that I do not have access to for now.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by chrisvidal** [comment]
Will come back to that in about one month.

**Comment by daftspunk** [comment]
Thanks mate!

**Pull request merged**
