### PR TITLE
User report widget

### PR DESCRIPTION
**Pull request by MatissJanis**
Displays user registrations and logins.
dashboard october cms

### CODE REVIEW

**Comment by daftspunk** [comment]
Wow, very cool!! We will merge this soon

**Comment by vojtasvoboda** [comment]
But when I login at 25. Jan 2015 and then 28. Jan 2015, I will lose access from 25.Jan 2015. So it's show only last successful logins, not overall logins :-( See https://github.com/MatissJanis/user-plugin/commit/587577ece1abdef05942808d190f27e746480960#diff-79a65bc84d48bd6ad8d53e9183305c25R36

I'm fixing it by my pull request https://github.com/rainlab/user-plugin/pull/111 to possible save all successfully logins to database by another plugin.

**Comment by daftspunk** [comment]
Yes OK, perhaps this is better as a standalone plugin.

**Comment by vojtasvoboda** [comment]
User registrations and logins dashboard widget are now part of the [User Access Log](http://octobercms.com/plugin/vojtasvoboda-useraccesslog) plugin. You can close this issue.

useraccesslog-screen3

**Pull request closed without merging**
