### PR TITLE
Allow usergroups to be deleted in the same way users can be.

### PR DESCRIPTION
**Pull request by joakimbo**
Changes: 

- Show checkboxes for usergroup list.
- Add delete button to list toolbar.
- Add delete function to UserGroup controller.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@JBonnyDev you don't have to close and reopen pull requests; just make the changes to the branch that you made the original PR with.

**Comment by JBonnyDev** [comment]
@LukeTowers Yeah I know I should, this was purely a preference move on how I want to manage my forked repo.

**Comment by JoakimBo** [comment]
@LukeTowers So after taking another look groups can be deleted in the same manner that administrators in the backend can (garbage can in right left corner). This PR could be closed but I would like to have a discussion on why the delete button is sort of tucked away and barely noticeable, I think its a UX problem. Would the best way to start those discussions be to open separate issues in the respective repos?

**Comment by LukeTowers** [comment]
The delete button is tucked away because it's supposed to be difficult to find is my guess, probably to avoid accidental deletions.

**Comment by JoakimBo** [comment]
Well, I would call that bad design, but perhaps that comes down to taste.

**Comment by LukeTowers** [comment]
It's open source, everything always open to PRs if you'd like to change the functionality :) @JoakimBo

**Comment by LukeTowers** [comment]
I like to bring up PRs because then it brings tangible specific ideas for improvement up instead of having to go back and forth for a while with theoreticals. That's all well and good for architecting or structuring systems however I usually find it more productive when discussing design changes / improvements to do that in the context of a tangible PR to change existing behaviour

**Pull request closed without merging**
