### PR TITLE
Make the User model notifiable

### PR DESCRIPTION
**Pull request by meysammahfouzi**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Isn't this something that should be handled by the [RainLab.Notify](https://github.com/rainlab/notify-plugin) plugin?

**Comment by meysammahfouzi** [comment]
@LukeTowers Since the `Notifiable` trait [is supported](https://laravel.com/docs/5.6/notifications#sending-notifications) by the default `App\User` model in Laravel, I think `RainLab User` should support it as well. Why should we remove a functionality provided by Laravel and then add it back by a plugin?

**Comment by LukeTowers** [comment]
Because the Authentication/User system in October is different than the one used by Laravel. October's `User` model does not implement Laravel's `App\User` model. @meysammahfouzi

**Comment by meysammahfouzi** [comment]
@LukeTowers Yes I know they are different. But conceptually, they should be the same, don't they? I think if we ever need to make a model notifiable, the user model would be the first one that may need notification, that's why `App\User` supports it by default because so many people would probably need it by default.

**Comment by LukeTowers** [comment]
They should ideally, but Laravel keeps switching their authentication implementation around and October hasn't kept up. There's a lot of work to be done to make them line up perfectly right now. The RainLab.Notify plugin is intended as an implementation of the Laravel notification system.

What happens when you add this line of code? Does everything work exactly as anticipated? What code do you use to trigger the behaviour?

**Comment by meysammahfouzi** [comment]
Yes, after adding that everything works as expected. I used the following to notify the user, and it worked:

`$user->notify(new SomeNotification());`

The following worked as well:

`Notification::send($user, new SomeNotification());`

Another solution is the inherit from `User` model and add the `Notifiable` trait to it:

```
use Illuminate\Notifications\Notifiable;
use RainLab\User\Models\User as FrontUser;

class NotifiableUser extends FrontUser
{
    use Notifiable;
}
```

Then:

`NotifiableUser::find($userId)->notify(new SomeNotification());`

Although the above works, I don't like it much. Another option as you suggested is to wrap the Notifiable trait in a behavior and then dynamically add that behavior the the `RainLab.User` model. Someone tried to do this, but it does not seem to work:

https://github.com/CptMeatball/notifiable-user
```
User::extend(function($model) {
     $model->implement[] = 'Meysam.Notification.Behaviors.Notifiable';
});
```

I used that above code and got this error when calling `Notification::send($user, ...)`:  

> Call to undefined method Meysam\Notification\Behaviors\Notifiable::morphMany()

**Comment by LukeTowers** [comment]
@meysammahfouzi that's because the trait expects to be attached directly to a model, not to a behavior that's attached to a model. See https://github.com/CptMeatball/notifiable-user/pull/1 for my attempt to make it work; which may not work if the scope of the method in question isn't public. If it works well and we can test it thoroughly, perhaps we could add the `__call()` magic to the October\Rain\Database\ModelBehavior class so that it's more intuitive in the future.

**Comment by meysammahfouzi** [comment]
@LukeTowers Thanks for the attempt. I tested it and got this error when calling `Notification::send`:

> Call to a member function orderBy() on null

notifications-error

Any ideas?

**Comment by LukeTowers** [comment]
@meysammahfouzi forgot a `return` statement; see https://github.com/LukeTowers/notifiable-user/commit/40ac9c9df5c25bb39d04d5013103b4706bb3acb1

**Comment by meysammahfouzi** [comment]
@LukeTowers  Great! It works now 👍

**Comment by LukeTowers** [comment]
Excellent @meysammahfouzi! What do you think about including that `__call()`logic in the base ModelBehavior class?

**Comment by meysammahfouzi** [comment]
@LukeTowers That would definitely make wrapping traits in behaviors easier. I'm not sure what unexpected side effects adding it might have though...

**Comment by LukeTowers** [comment]
Exactly; which is why I'm leery about just going ahead and doing it though; perhaps I'll talk to @daftspunk about it

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Pull request closed without merging**
