### PR TITLE
Implement remember login mode choice

### PR DESCRIPTION
**Pull request by KGE**
Improves #269 

Inspired by [backend version](https://github.com/octobercms/october/pull/2924)

@LukeTowers I think this is a nice starting point

### CODE REVIEW

**Comment by manuelbua** [comment]
This would be a nice addition, any chance to have this merged upstream?

**Comment by LukeTowers** [comment]
@manuelbua have you tested these changes locally? Could you send screenshots of the login form with the checkbox and the backend settings for this? Please test all three modes (Yes, No, Ask) and verify that they work correctly.

**Comment by manuelbua** [comment]
@LukeTowers, you [explicitly asked](https://github.com/rainlab/user-plugin/pull/269#issuecomment-362950766) for a PR resubmission and were also looking forward at merging it: i genuinely asked about it, because i thought it was going to happen.

**Comment by LukeTowers** [comment]
@manuelbua it is going to happen; however I don't have time to test this myself personally right this moment so I'm asking you to do it for me.

**Comment by Eoler** [comment]
I tried it and it works (and most sensible setting is "ask", of course). 
It goes to production site tomorrow... thanks, @KGE !

**Comment by Eoler** [comment]
This goodness still works with the latest plugin release, @bennothommo

**Comment by bennothommo** [comment]
@Eoler Are you saying that this PR works with the latest version of the plugin?

**Comment by Eoler** [comment]
Exactly, @bennothommo (ok, I didn't try 5 years expiry ;)
Its very handy with e-commerce sites, where security matters more...

**Comment by bennothommo** [comment]
Thanks for letting us know, @Eoler. I'll give it a test and merge it once reviewed.

**Comment by bennothommo** [comment]
@KGE I have tested this and it works very well - great job on this. I've merged in the `master` branch to resolve some conflicts, and also changed the "Yes" and "No" terms for the remember mode to "Always" and "Never", to make it more clear what the options mean in terms of setting a persistent session.

**Pull request merged**
