### PR TITLE
Added additional password validation

### PR DESCRIPTION
**Pull request by dzapek**
The User model used the beforeValidate method and wrote property rules there, which made their modification difficult or impossible. 
I added a password policy in the settings and implemented additional validation rules. In addition, I used the addValidationRule method so as not to modify the existing rules.

Best regards
Patryk Trąd

### CODE REVIEW

**Comment by daftspunk** [comment]
Hi Patryk, this looks good from our side.  Let me know when it is ready to be merged.

**Comment by dzapek** [comment]
Hi @daftspunk , is now ready to merge

**Comment by dzapek** [comment]
Thanks for merging. May I also ask you to add a new tag for us to install it using the version in composer?

**Comment by acasar** [comment]
This just crashed all our projects... Still investigating and will come back with more info

**Comment by acasar** [comment]
The error is: 
```
Call to undefined method addValidationRule()
```

**Comment by jan-vince** [comment]
@dzapek @acasar @daftspunk 

I can confirm that this is not working in OC1 :(

**Comment by daftspunk** [comment]
This should fix it 

https://github.com/rainlab/user-plugin/commit/e213b97e523e1b3f527afbe19e5ab2116b5e225d

**Comment by daftspunk** [comment]
Related https://github.com/rainlab/user-plugin/pull/509

**Pull request merged**
