### PR TITLE
Add First, Last, Middle Initial to users

### PR DESCRIPTION
**Pull request by firemankurt**
To have any meaningful way to sort and find users it is important to have at least First and Last name fields.
If you feel it is too invasive we could always make it an option in settings for site owners to decide what they want to require and use.  It is a major stumbling block if every developer has to come up with their own user name extension and scheme.  It would be easier for most if the rainlab.user plugin sets this basic standard.

### CODE REVIEW

**Comment by gergo85** [comment]
If you need additional fields, you can add them using plugin. My user plugin will be available on the official Marketplace. The public repository: https://github.com/gergo85/oc-user-plus

**Comment by firemankurt** [comment]
I appreciate the offer gergo85 but the reason I decided to do a PR on rainlab.user instead of adding the fields myself is that I believe that this is such a basic requirement that it should be standard in rainlab.user.   If I add FL name fields in my plugin and you add the same fields in yours and someone else adds them in theirs then who's plugin should future developers rely on?  Lets just add them to rainlab so everyone can move past this and know where to find these basic fields.  I'm interested to see what daftspunk thinks of this idea.

**Comment by gergo85** [comment]
I agree with you but the question is, which are the basic fields? Indeed, the FL fields are used many cases. I am waiting for daftspunk's opinion too.

**Comment by firemankurt** [comment]
I don't even care if the fields are added in the forms.  I just want them in DB so we can all reference them and use the same consistent resource for storage.

**Comment by firemankurt** [comment]
Here is a plugin that adds those fields without affecting much else.  Anyone is welcome to it.
https://github.com/firemankurt/flmames

**Comment by daftspunk** [comment]
We have recently added "surname" to the users table. This comfortably allows itself to be optional.

You can choose either:

- to use "name" only
- to use "name" and "surname"

**Pull request closed without merging**
